# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ProjetoFinal' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Alamofire', '~> 5.4.1'
  pod 'AlamofireImage', '~> 4.1.0'
  pod 'SwiftLint'
  pod 'CommonsService',
  :git => 'https://github.com/leticiassiqueira25/Commons.git',
  :branch => 'master'
  pod 'DetalhesMoedas',
  :git => 'https://github.com/letyciamarques/DetalhesMoeda.git',
  :branch => 'develop'
  
  target 'ProjetoFinalTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ProjetoFinalUITests' do
    # Pods for testing
  end

end
